frases_pastilhas_freio = [
    'Quando eu freio, o carro faz um barulho estranho, como se estivesse rangendo.',
    'Parece que o pedal do freio está mais baixo do que antes, tenho que apertar mais para o carro parar.',
    'Meu carro está demorando mais para parar quando eu piso no freio.',
    'Estou ouvindo um som metálico quando freio, como se algo estivesse raspando.',
    'Parece que os freios estão meio moles, não estão funcionando como antes.',
    'O carro treme um pouco quando eu aperto o freio.',
    'Notei que o freio está fazendo um barulho chiado toda vez que eu uso.',
    'Preciso usar mais força no pedal para frear, não era assim antes.',
    'Tem algo errado com os freios, eles não parecem tão confiáveis como antes.',
    'Ouvi dizer que pode ser as pastilhas de freio, porque está fazendo muito barulho quando eu paro o carro.',
    'Estou sentindo um cheiro estranho depois de usar os freios.',
    'Acho que o carro está puxando para um lado quando eu freio.',
    'Tem um barulho agudo toda vez que piso no freio, parece um apito.',
    'O freio está dando uns trancos, como se estivesse falhando.',
    'O pedal do freio está vibrando quando eu tento parar o carro.',
    'Sinto como se o carro estivesse escorregando um pouco quando eu freio.',
    'Os freios estão fazendo um barulho como se tivesse areia neles.',
    'Estou percebendo que o freio está mais sensível, qualquer toque faz o carro parar bruscamente.',
    'Parece que algo está raspando quando eu piso no freio, como se tivesse uma pedra presa.',
    'O carro não está parando suavemente, está meio brusco, especialmente em baixa velocidade.',
    'Estou percebendo que o freio está mais duro, tenho que fazer mais força para parar o carro.',
    'Parece que o carro está dando uma leve derrapada quando freio em curvas.',
    'O freio está fazendo um som como se estivesse arranhando alguma coisa.',
    'Sinto que o carro não para com a mesma eficiência, demora mais para desacelerar.',
    'Ouço um chiado constante, principalmente quando estou quase parando.',
    'Parece que tem algo raspando dentro da roda quando piso no freio.',
    'O pedal do freio está tremendo quando tento parar em uma descida.',
    'O carro faz um barulho de metal com metal, principalmente quando freio de repente.',
    'O freio está começando a falhar, às vezes tenho que pisar várias vezes para funcionar.',
    'Estou notando um barulho de raspagem vindo das rodas toda vez que freio levemente.',
    'Parece que o freio está mais mole, ele afunda mais do que antes quando piso.',
    'O carro faz um barulho de atrito toda vez que paro em uma ladeira.',
    'Notei que o carro dá uma balançada quando freio de leve.',
    'O pedal do freio está ficando cada vez mais difícil de apertar.',
    "Estou ouvindo um som estranho, como se fosse um 'toc toc', toda vez que paro.",
    'Quando piso no freio, parece que tem algo raspando na roda da frente.',
    'O freio está com uma resposta lenta, demoro mais tempo para parar completamente.',
    'Sinto uma vibração forte no volante quando aperto o freio.',
    'Quando piso no freio, parece que o carro está puxando para a direita.',
    'Estou notando que o carro não está parando de forma suave, ele dá uns trancos.',
    'O freio está fazendo um barulho contínuo, parece que está raspando em algo.',
    'Toda vez que freio, ouço um estalo vindo da parte de trás do carro.',
    'O carro está demorando mais para parar em semáforos, isso não acontecia antes.',
    'Estou sentindo um cheiro de queimado quando freio muito.',
    "O carro parece estar 'deslizando' um pouco quando paro rapidamente.",
    'O pedal do freio está fazendo um som de ar saindo, como se estivesse vazando.',
    'Toda vez que freio em alta velocidade, sinto o carro tremer.',
    'Parece que tem algo solto na roda, porque faz um barulho quando freio.',
    'O carro dá um solavanco quando freio bruscamente.',
    'Estou notando que os freios fazem um barulho diferente quando estão quentes.']

frases_velas_ignicao = [
    'O carro está falhando e dando uns trancos quando acelero.',
    'Parece que o motor está engasgando, especialmente quando eu tento acelerar rápido.',
    'Estou notando que o carro está demorando mais para pegar quando ligo.',
    'O motor está fazendo um barulho estranho, como se estivesse batendo.',
    'Sinto que o carro perdeu potência, ele não está acelerando como antes.',
    "Parece que o carro está 'engasgando' quando eu tento subir uma ladeira.",
    'O consumo de combustível aumentou, estou tendo que abastecer com mais frequência.',
    'O carro está tremendo quando eu paro no semáforo, como se fosse desligar.',
    'Está saindo um cheiro forte de combustível quando eu tento dar a partida.',
    'Parece que o motor está funcionando irregularmente, como se estivesse falhando em algumas rotações.',
    'O carro está dando umas falhadas quando eu tento manter uma velocidade constante.',
    "O motor parece estar 'piscando', às vezes funciona bem, às vezes não.",
    'Estou percebendo que o carro está vibrando mais que o normal, principalmente em baixa velocidade.',
    'O carro não está arrancando direito, fica meio lento no começo.',
    'Está saindo muita fumaça do escapamento quando eu ligo o carro.',
    'O motor parece estar fazendo mais barulho do que o normal, como se estivesse mais áspero.',
    'Sinto que o carro está meio pesado, não responde bem ao acelerador.',
    'Quando estou em marcha lenta, o motor fica instável, como se fosse morrer.',
    'O carro está perdendo potência em subidas, parece que não tem força.',
    'O motor está demorando para responder quando eu piso no acelerador, tem um atraso.',
    'O carro está engasgando quando tento acelerar de repente.',
    "Parece que o motor está 'falhando' quando estou na estrada, como se perdesse força de vez em quando.",
    'O carro está difícil de ligar nas manhãs frias, preciso tentar várias vezes.',
    'Estou ouvindo uns estalos estranhos vindos do motor quando estou dirigindo.',
    'Sinto que o carro está tremendo mais ao parar em um semáforo ou sinal de trânsito.',
    "O motor fica meio 'grosso' quando estou em marcha lenta, não fica funcionando redondo.",
    'O carro está perdendo velocidade mesmo com o pé no acelerador, parece que não vai.',
    'Tem horas que o motor faz uns barulhos de estalo quando tento acelerar.',
    'Estou percebendo um cheiro de gasolina mais forte do que o normal, especialmente quando ligo o carro.',
    'O carro está puxando mais para o lado quando acelero, parece que o motor não está distribuindo bem a potência.',
    'O carro está hesitando quando eu tento acelerar, como se não estivesse recebendo combustível suficiente.',
    'Parece que o motor está pulando quando eu mantenho a velocidade constante, como se estivesse perdendo o ritmo.',
    'O carro está com dificuldade para manter a marcha lenta, fica oscilando como se fosse apagar.',
    'Está saindo uma fumaça azulada pelo escapamento, especialmente quando o carro está frio.',
    'O motor faz um barulho de estalo quando eu ligo o carro, principalmente nas primeiras vezes do dia.',
    'O carro está vibrando muito quando eu acelero, como se estivesse desbalanceado.',
    'Quando eu acelero rápido, o carro hesita e depois dá um pulo.',
    'Sinto que o carro está meio fraco nas acelerações, como se tivesse menos potência.',
    'O carro está difícil de ligar em dias frios, o motor parece não querer pegar.',
    'O motor faz um som estranho, como se estivesse batendo metal, quando estou devagar.',
    "O carro está fazendo um barulho de 'clique' quando eu tento acelerar de repente.",
    'O carro está demorando para alcançar a velocidade que eu quero, como se estivesse puxando devagar.',
    "O motor está funcionando de forma irregular, como se estivesse 'engasgando' ao acelerar.",
    'Está saindo um cheiro de óleo queimado quando o carro está parado.',
    'O carro está falhando quando eu tento acelerar rápido, como se não estivesse respondendo.',
    "O motor está tremendo e fazendo um som de 'ronco' quando eu tento manter uma velocidade alta.",
    'O carro está soltando fumaça preta pelo escapamento, especialmente quando eu acelero.',
    'Quando estou na estrada, o carro parece perder potência de vez em quando, como se estivesse lutando para manter a velocidade.',
    'O carro está com dificuldade para subir ladeiras, parece que não tem força suficiente.',
    "O motor está funcionando de forma irregular, como se estivesse 'piscando' em termos de potência e resposta."
]

frases_transmissao = [
    'O carro está demorando para trocar de marcha, parece que fica preso em uma marcha por mais tempo.',
    'Estou sentindo uns trancos quando a transmissão muda de marcha, principalmente em baixa velocidade.',
    'O carro faz um barulho estranho, como se estivesse zumbindo ou assobiando, quando acelero.',
    'A transmissão está patinando, o motor acelera mas o carro não responde como deveria.',
    'Estou notando que o carro está perdendo potência quando muda de marcha.',
    'O câmbio está ficando difícil de engatar, especialmente quando o carro está frio.',
    'Parece que a marcha não está engatando direito, tenho que tentar várias vezes para funcionar.',
    'O carro dá uns solavancos quando muda de marcha, como se estivesse pulando.',
    'A luz de verificação do motor acendeu e acho que é algo relacionado à transmissão.',
    'Está saindo um cheiro de queimado, especialmente depois de dirigir por um tempo.',
    'O carro está trocando de marcha sozinho.',
    'Sinto um solavanco toda vez que muda de marcha.',
    'A marcha não está entrando direito, fica presa.',
    'O carro demora para acelerar depois de mudar de marcha.',
    'Ouço um barulho estranho quando troco de marcha.',
    'O câmbio está duro, difícil de mexer.',
    'Parece que a marcha escapa sozinha às vezes.',
    'O carro está patinando quando tento acelerar.',
    'Sinto o carro tremer quando muda de marcha.',
    'O câmbio não está respondendo como deveria.',
    'O carro dá um tranco quando coloco em drive.',
    'A marcha está pulando sozinha para neutro.',
    'O câmbio faz um clique estranho quando troco de marcha.',
    'O carro está vibrando quando passa de marcha.',
    'Parece que o carro está hesitando para mudar de marcha.',
    'O câmbio não está engatando suavemente.',
    'O carro perde força nas subidas, mesmo com a marcha engatada.',
    'Está difícil tirar o carro da ré.',
    'A transmissão está fazendo um som de arranhado.',
    'O carro fica acelerando sem ganhar velocidade.',
    'O carro está ficando lento para acelerar depois de uma parada.',
    'O câmbio faz um barulho metálico quando troco de marcha.',
    'Estou sentindo uma vibração estranha no volante ao mudar de marcha.',
    'O carro está hesitando antes de engatar a marcha.',
    'A transmissão parece estar escorregando quando eu acelero forte.',
    'O carro está trocando de marcha mais frequentemente do que o normal.',
    'A marcha está difícil de desengatar quando estou em movimento.',
    'Sinto um cheiro estranho quando o carro está acelerando.',
    'O carro está fazendo um som de batida quando muda de marcha.',
    'O câmbio não está respondendo rapidamente quando eu mudo de marcha.',
    'A transmissão faz um barulho de arranhado quando o carro está em alta velocidade.',
    'O carro está pulando ao acelerar em subidas.',
    'A luz de transmissão está piscando no painel.',
    'O câmbio faz um som de estalo quando engata a marcha.',
    'Sinto um solavanco quando o carro tenta acelerar após uma parada.',
    'A transmissão não está engatando de forma suave durante a troca de marchas.',
    'O carro está perdendo força ao subir uma ladeira com a marcha engatada.',
    'O câmbio está travando às vezes quando tento mudar a marcha.',
    'O carro está emitindo um som de ruído quando a marcha está engatada.',
    'A marcha não está trocando corretamente, fica oscilando entre as marchas.'
]

frases_alinhamento = [
    "Meu carro está puxando para a direita.",
    "Meu carro está puxando para a esquerda.",
    "Meu volante está dando toquinhos.",
    "Meu volante está puxando para o lado.",
    "Meu volante está virando sozinho.",
    "Meu volante não está ficando na direção correta.",
    "Volante fazendo movimentos sozinho.",
    "Volante vira sozinho.",
    "Volante virando pra direita.",
    "O carro está puxando sozinho para a direita.",
    "Parece que o carro quer virar para a esquerda sozinho.",
    "Eu sinto o volante meio solto, ele vai pra um lado sozinho.",
    "Quando solto o volante, ele desvia.",
    "Sinto o volante tremer quando acelero.",
    "O carro fica inclinando para um lado enquanto dirijo.",
    "A direção parece pesada de um lado e leve do outro.",
    "O volante parece desbalanceado, ele não fica reto.",
    "Toda vez que freio, o carro puxa pro lado.",
    "Tenho que ficar corrigindo a direção o tempo todo.",
    "O carro parece que vai sair da pista quando acelero.",
    "Preciso segurar o volante com força, senão ele vai pro lado.",
    "Quando viro, o volante não volta sozinho.",
    "O carro fica mais difícil de controlar em linha reta.",
    "O carro parece que está dançando na pista.",
    "Quando acelero, parece que o carro pende pra direita.",
    "O volante não fica firme, ele fica dando uns trancos.",
    "Sinto o carro balançar de um lado para o outro.",
    "Quando viro, o volante parece resistir.",
    "Acho que os pneus estão gastos porque o carro puxa pro lado.",
    "Preciso forçar o volante para ele ficar reto.",
    "O carro não segue em linha reta mesmo na pista plana.",
    "Parece que algo está errado com a direção, ela não obedece direito.",
    "Sinto que a direção está meio descontrolada.",
    "O volante parece que dá uns pulinhos, não está suave.",
    "Quando faço curva, o carro não responde bem.",
    "Dirigir em linha reta está sendo um desafio.",
    "Sinto o carro meio torto quando estou dirigindo.",
    "O volante parece meio duro, não consigo virar facilmente.",
    "Quando acelero rápido, o carro balança pro lado.",
    "O carro não está andando reto, parece que está puxando.",
    "O volante parece estar com folga, ele mexe sozinho.",
    "Tenho a sensação de que o carro está escorregando na pista.",
    "Quando passo por lombadas, o volante dá umas mexidas.",
    "O carro faz um barulho esquisito toda vez que tento virar o volante.",
    "Parece que a direção está desalinhada, não consigo controlar bem.",
    "Toda vez que viro o volante, parece que ele trava um pouco.",
    "O carro não responde bem quando faço curvas, parece pesado.",
    "Sinto o volante vibrando quando estou em alta velocidade."
]

frases_superaquecimento_motor = [
    "Saiu uma fumaça estranha do capô do carro.",
    "O painel do carro mostrou que a temperatura está alta.",
    "A ventoinha do carro não para de fazer barulho.",
    "O ar-condicionado só sai quente, mesmo estando no frio.",
    "Tem uma poça de água colorida embaixo do carro.",
    "O motor ficou muito quente de repente.",
    "O carro está esquentando demais, o ponteiro da temperatura não desce.",
    "Tem vapor saindo do capô.",
    "Parece que o carro tá fervendo.",
    "O ar do ar-condicionado tá saindo quente.",
    "A ventoinha tá ligando direto, mais do que o normal.",
    "Notei um líquido azul no chão da garagem.",
    "O carro tá fazendo muito barulho e parece que está muito quente.",
    "A temperatura no painel subiu e não desce mais.",
    "Senti um cheiro estranho vindo do motor.",
    "O capô tava muito quente e saindo fumaça.",
    "A luz de temperatura no painel acendeu.",
    "Tem algo pingando embaixo do carro, parece ser colorido.",
    "O motor parece que vai derreter de tão quente.",
    "A ventoinha do motor não para de rodar.",
    "A água do radiador parece que tá vazando.",
    "O ar-condicionado só sopra ar quente.",
    "O carro tá aquecendo muito rápido.",
    "O painel mostrou que o motor tá esquentando demais.",
    "Saiu vapor do motor quando parei o carro.",
    "Tem um líquido estranho, azul ou vermelho, embaixo do carro.",
    "A ventoinha tá fazendo muito barulho ultimamente.",
    "O carro começou a esquentar e o ar parou de funcionar.",
    "Notei que a temperatura no painel subiu do nada.",
    "Vi uma fumaça saindo do capô enquanto dirigia.",
    "O motor tá fervendo, não tá normal.",
    "A luz da temperatura do motor acendeu.",
    "O ar-condicionado parece que não tá gelando mais.",
    "Tem um vazamento embaixo do carro com água colorida.",
    "A ventoinha tá ligada o tempo todo e fazendo barulho.",
    "A temperatura subiu e agora o carro não esfria mais.",
    "Vi um vapor estranho subindo do capô.",
    "A luz do painel de temperatura tá acesa direto.",
    "Tem água vazando embaixo do carro, meio colorida.",
    "O carro tá esquentando muito mais do que o normal.",
    "O capô ficou tão quente que não consegui nem encostar.",
    "A ventoinha não para, parece que tá ligado o tempo todo.",
    "Senti um cheiro de queimado vindo do motor.",
    "O carro tá fervendo e saindo vapor do capô.",
    "O ponteiro da temperatura foi lá pra cima e não voltou.",
    "A ventoinha do motor tá funcionando sem parar.",
    "Notei que tem água vazando perto do radiador.",
    "O ar que sai do ar-condicionado tá quente.",
    "Vi uma fumaça saindo do motor depois de dirigir.",
    "O motor tá muito quente e tem um líquido colorido vazando."
]

frases_bateria = [
    "O carro está demorando muito para ligar, parece que tá forçando demais o motor.",
    "As luzes do carro estão piscando e meio fracas.",
    "O ar-condicionado não está funcionando direito, e o carro demora pra pegar.",
    "A luz da bateria no painel acendeu, não sei o que isso quer dizer.",
    "Parece que o motor está pesado toda vez que tento ligar o carro.",
    "O carro faz um barulho estranho e demora pra ligar.",
    "Quando tento dar a partida, parece que o motor não tem força suficiente.",
    "O painel tá mostrando uma luz da bateria, acho que tem algo errado.",
    "O carro não liga de primeira, parece que tá com dificuldade.",
    "As luzes internas do carro estão oscilando, e o motor demora a pegar.",
    "Sinto que o carro tá mais lento pra ligar do que o normal.",
    "O motor tá pesado na hora de dar partida, demora pra pegar.",
    "A bateria no painel tá acendendo e o carro não liga de primeira.",
    "As luzes do painel estão fracas, e o carro demora pra dar partida.",
    "Quando ligo o carro, as luzes do farol ficam piscando e o motor tá estranho.",
    "Tento ligar o carro e parece que a bateria não tá dando conta.",
    "O ar-condicionado tá fraco e o carro demora pra ligar.",
    "A luz da bateria acendeu no painel, e o motor tá demorando muito pra pegar.",
    "Parece que o motor tá travado quando dou a partida, tá muito lento.",
    "O carro tá meio estranho pra ligar, faz um barulho fraco e demora.",
    "As luzes externas do carro estão oscilando, e o motor tá pesado pra ligar.",
    "O carro demora muito pra pegar, acho que tem algo errado na bateria.",
    "Senti que o ar-condicionado tá mais fraco, e o carro não pega de primeira.",
    "A luz da bateria do painel acendeu, e o carro tá tendo dificuldade de ligar.",
    "Quando ligo o carro, o motor faz um esforço muito grande pra funcionar.",
    "O carro faz um barulho estranho na hora de ligar e demora pra pegar.",
    "As luzes do painel estão oscilando e o motor parece que tá sem força.",
    "A luz da bateria no painel acendeu e o carro tá demorando pra dar partida.",
    "O motor não pega direito e faz um barulho estranho na hora de ligar.",
    "Parece que o carro tá sem força pra ligar, e as luzes estão fracas.",
    "O motor tá demorando pra pegar, e a luz da bateria no painel acendeu.",
    "Toda vez que tento ligar o carro, parece que a bateria tá fraca.",
    "As luzes estão piscando e o carro faz um barulho estranho pra pegar.",
    "Demoro pra conseguir ligar o carro, e o motor parece que tá pesado.",
    "O carro não pega de primeira, as luzes estão fracas, e o motor tá estranho.",
    "A bateria no painel acendeu e o motor não tá pegando direito.",
    "Parece que o carro não tem força suficiente na hora de ligar.",
    "As luzes do painel tão oscilando e o carro tá demorando muito pra pegar.",
    "O carro faz um barulho fraco e demora pra ligar, acho que é a bateria.",
    "Tentei ligar o carro e parece que o motor não tem energia suficiente.",
    "As luzes internas estão piscando, e o carro demora muito pra pegar.",
    "O motor tá pesado quando tento ligar, e a luz da bateria acendeu.",
    "O carro tá demorando pra ligar e as luzes estão bem fracas.",
    "O carro não pega direito e o painel mostra uma luz da bateria acesa.",
    "Tento ligar o carro, mas o motor faz um barulho fraco e demora muito.",
    "As luzes do carro estão piscando, e o motor tá muito lento pra ligar.",
    "A luz da bateria tá acesa e o carro não pega de primeira.",
    "O carro faz um barulho fraco quando tento ligar e demora muito pra pegar.",
    "As luzes internas estão oscilando, e o motor parece que tá sem força.",
    "O motor tá pesado pra ligar e o painel mostra a luz da bateria acesa.",
]

frases_cambio = [
    "Quando eu mudo de marcha, parece que o carro dá um tranco e fica meio nervoso",
    "Às vezes, tenho que esperar um pouco para conseguir engatar a marcha",
    "O carro faz um barulho estranho, tipo um 'clunk', quando eu troco a marcha",
    "Vi uma luz de transmissão no painel que não sei o que significa, parece um problema",
    "A marcha parece que não entra de imediato, fica meio emperrada",
    "O carro faz um som esquisito quando estou mudando as marchas",
    "Uma luz de alerta laranja com um símbolo de engrenagem acendeu no painel",
    "Quando mudo de marcha, parece que o carro dá uma sacudida",
    "Eu sinto que o carro está demorando mais para engatar a próxima marcha",
    "Faz um barulho como se estivesse raspando quando troco de marcha",
    "A luz de 'check engine' acendeu no painel e não sei por quê",
    "O câmbio fica meio difícil de mexer, não engata direito às vezes",
    "Ouço um ruído meio metálico quando troco as marchas",
    "Uma luz amarela com um triângulo no painel está acesa e piscando",
    "Quando eu mudo de marcha, parece que o carro dá um solavanco",
    "Eu sinto que a marcha não está entrando suavemente como antes",
    "Tem um barulho como se algo estivesse batendo quando troco a marcha",
    "Uma luz de advertência com um símbolo de um câmbio acendeu no painel",
    "Quando estou dirigindo, o câmbio às vezes parece travar um pouco",
    "O carro está fazendo um som estranho quando tento mudar a marcha",
    "A luz do painel com um símbolo de engrenagem está piscando",
    "Sinto que a marcha não está engatando corretamente e demora",
    "O carro faz um barulho incomum durante a troca de marcha",
    "Uma luz vermelha com um ponto de exclamação apareceu no painel",
    "O câmbio parece estar meio solto e não responde como deveria",
    "Quando mudo de marcha, o carro parece ter dificuldade e faz barulho",
    "Uma luz amarela com um símbolo de um carro com chave está acesa",
    "O carro dá um puxão estranho quando engato a marcha",
    "O câmbio parece meio duro e difícil de engatar às vezes",
    "Faz um barulho esquisito como se estivesse rangendo quando troco a marcha",
    "Uma luz de alerta vermelha com um símbolo de transmissão apareceu no painel",
    "Quando vou mudar de marcha, o carro faz um som de engrenagem",
    "A marcha não entra suavemente, parece que está travando",
    "Uma luz laranja com um ícone de engrenagem está acesa e piscando",
    "O carro faz um barulho alto quando estou mudando de marcha",
    "Sinto que a marcha está meio lenta para engatar, e o carro hesita",
    "O carro faz um som estranho de metal quando troco a marcha",
    "Uma luz de advertência amarela com um símbolo de engrenagem está piscando",
    "Quando mudo de marcha, parece que o carro está se esforçando demais",
    "O câmbio está difícil de movimentar e parece que está preso",
    "O carro faz um barulho como se estivesse raspando quando engato a marcha",
    "Uma luz laranja com um símbolo de um carro com uma chave está acesa",
    "Quando vou mudar a marcha, o carro parece hesitar e faz um barulho",
    "Uma luz de alerta vermelha com um ícone de um câmbio está piscando",
    "Sinto um tranco estranho no carro quando troco de marcha",
    "O câmbio está fazendo um som estranho como se estivesse quebrando",
    "Uma luz de advertência com um símbolo de um câmbio e uma exclamação acendeu",
    "Quando engato a marcha, o carro faz um som de 'clunk' e não engata direito",
    "A marcha não entra de forma suave e o carro faz um barulho estranho",
    "Uma luz de transmissão com um símbolo de uma engrenagem está piscando no painel",
]